### ISSUE TITLE
"No plugins found for slaffik" displayed for Themes

### ISSUE THREAD

**Issue by slaFFik** [easydigitaldownloads/wp-tally#11]
Example: http://wptally.com/api/slaffik

IMO "No themes found ..." should be there.

**Comment by michaelbeil** [comment]
:+1:

**Comment by slaFFik** [comment]
Ерыш issue is still live.

**Comment by deviodigital** [comment]
Yup, I see that too. On the website, it shows 'themes' now, but it looks like the API is still showing 'plugins'

**Comment by ghost1227** [comment]
This has been fixed (updating site shortly)
