### ISSUE TITLE
Add "Active Installs"

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/wp-tally#13]
See title.

**Comment by deviodigital** [comment]
I'd love to help with this, but I've downloaded the repository and copied the 'view source' from wptally.com and have been running that locally, and nothing is showing when I submit a username.

Is there any info on how to run this locally so I can test out if the active installs code I add in works first before I PR?

**Comment by deviodigital** [comment]
Also, maybe it's just me and I'm completely overlooking / looking in the wrong place, but I'm checking out the WordPress API and it doesn't look like active installs are in it?

[easy digital downloads example](https://api.wordpress.org/plugins/info/1.0/easy-digital-downloads.json)

I'm out of my element here a bit, so if I'm way off, someone just let me know lol

**Comment by michaelbeil** [comment]
I would say submit a PR @deviodigital. I am not sure how everything with the wptally API is set up, but then the code will be on the team's radar.

**Comment by deviodigital** [comment]
:+1:

**Comment by ghost1227** [comment]
Merged, thanks!
